# Generated by Django 3.0.1 on 2020-04-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_historicalbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='historicalbook',
            name='cover',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
