# Generated by Django 3.0.1 on 2020-04-15 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200414_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special_status', 'Can read all books')]},
        ),
        migrations.DeleteModel(
            name='HistoricalBook',
        ),
    ]
